### ISSUE TITLE
AppScan code sweep action doesn't run scanning on code

### ISSUE THREAD

**Issue by 1633605** [HCL-TECH-SOFTWARE/appscan-codesweep-action#7]
Hi,

I have followed your documentation and configured the workflow with secrets generated for API Key and secret via the URL: https://cloud.appscan.com/main/settings

once the action is executed it shows the below information in log.

Run HCL-TECH-SOFTWARE/appscan-codesweep-action@v1
  with:
    asoc_key: ***
    asoc_secret: ***
    status: failure
  env:
    GITHUB_TOKEN: ***
/usr/bin/docker run --name hclcrioappscancodesweepactionlatest_7cd3e4 --label 7b361e --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_ASOC_KEY -e INPUT_ASOC_SECRET -e INPUT_STATUS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_DEBUG -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/calculator-api/calculator-api":"/github/workspace" hclcr.io/appscan/codesweep-action:latest
Not interested in this event: null.
Exiting...
##[debug]Docker Action run completed with exit code 0

Could you please let us know if there is something missed in terms of configuration here?

**Comment by mattmurp** [comment]
Hi,

What event(s) did you set your workflow to run on?  You'll want to use the pull_request event.  If you've already done that, can you show the yaml file you're using?

**Comment by 1633605-Phaneendra** [comment]
Hi,
Thanks for swift response. I have used for push event and below config.
on:
  push:
    branches: [ appscan* ]

Does it work only no pull request?

**Comment by mattmurp** [comment]
Hi,
Right now it only works for the pull_request event.

**Comment by 1633605-Phaneendra** [comment]
Ah Ok ! I will try with pull request then,

Out of curiosity to understand where is the config or control to make this action work only on PR. From the repo it has only action.yml which launches a docker container. Does that container has kind of control to make it work only for PR?

**Comment by mattmurp** [comment]
That's correct.  Until we support other events, I'll look to make the message more clear.  Right now it shows:
"Not interested in this event: null."
That should show the event you used (i.e. "push") but it's showing null for some reason.

**Comment by 1633605-Phaneendra** [comment]
Great ! Can we have read access to your action to understand the event based action setup?

**Comment by mattmurp** [comment]
I'm hoping to add the action code to the GitHub repo soon, but for now, I'm not able to do so.

**Comment by 1633605-Phaneendra** [comment]
I have used the pull request event as you suggested and the workflow is successful. and log here.
Checking for added files...
Checking for modified files...
Connecting to ASoC...
Running Codesweep security scan on updated files...

Few queries out of this execution as below.
1. Does the scan runs only for change set of files part of the pull request or it has possibility to run scan all the source code files part of the repo?
2. After the workflow run have been to the Dashboard (https://cloud.appscan.com/main/scans), But didn't see any scan run here. Is it due to no change in source code as per the event trigger?
3. How do i run the full scan and see the results back in the dashboard?
Please advise us.

**Comment by coadaflorin** [comment]
@1633605-Phaneendra 
1. The GitHub Action only scans new/changed code. It does not scan other files. 
2. Currently there is no direct integration between GitHub & ASoC. It is planned, but not yet available. Results will only be in GitHub. 
3. Depending on which toolset you use we recommend using the CLI, AppScan Go, maven/Gradle or one of the other CI/CD plugins like Jenkins, Azure DevOps ,etc. You can find a list of plugins here (https://cloud.appscan.com/plugins)

**Comment by 1633605-Phaneendra** [comment]
@coadaflorin  Thanks for the feedback.

As you mentioned that results are only available within github, does it in log or any other format or report available with in github?

**Comment by coadaflorin** [comment]
At the moment only the results you see in the actions/pull request are available.

**Comment by mattmurp** [comment]
In version 2 we've added the option to publish issues found to AppScan on Cloud when the PR is merged. See the [ReadMe](https://github.com/HCL-TECH-SOFTWARE/appscan-codesweep-action/blob/master/README.md) for additional details.
